### ISSUE TITLE
ftdispi_open: interface is not read

### ISSUE THREAD

**Issue by nononame** [ynsta/libftdispi#5]
A very simple bug fix. In the function ftdispi_open, the interface parameter is not used in the call to ftdi_set_interface.

You can pull my repository:
https://www.le-huit.fr/dev/libftdispi.git

And see the patch:
https://www.le-huit.fr/dev/libftdispi/git/master/961e948837b4d99d2d75e9cebe2613ec8cb01fa5/

This bug happens just when another interface than A is used.

Simon.

**Comment by ynsta** [comment]
Thank you

**Comment by nononame** [comment]
Maybe the [issue](https://github.com/ynsta/libftdispi/issues/1) is now resolved.

It uses:

`if( 0==ftdispi_open(&fsc, &fc, INTERFACE_B))`

and before your commit, INTERFACE_B was not read.

Thanks for your lib, it is very useful,
Simon.
